include(NcgAddTest)

add_subdirectory(core)
add_subdirectory(io)
add_subdirectory(body)
add_subdirectory(recon)
add_subdirectory(geom)
add_subdirectory(select)
add_subdirectory(record)
add_subdirectory(mesh)
add_subdirectory(material)
add_subdirectory(rig)
add_subdirectory(runtime)
add_subdirectory(fit)
add_subdirectory(nerf)
add_subdirectory(golden)
